---
title: "Appendix: Trends in age-adjusted mortality rates for blacks and whites by cause and sex, 1969-2013, United States"
output: html_document
---

Corinne A Riddell, PhD

Department of Epidemiology, Biostatistics and Occupational Health, McGill University, Montreal, Canada.

Address correspondence to: Corinne Riddell, PhD, Department of Epidemiology, Biostatistics & Occupational Health, McGill University, 1020 Pine Avenue West, Room 36B, Montreal, QC H3A 1A2, Canada. Email: <corinne.riddell@mail.mcgill.ca>

```{r load_libraries, echo=FALSE, warning=F, message=F}
library(dplyr)
library(purrr)
library(ggplot2)
library(stringr)
library(reshape2)
library(grid)
library(gridExtra)
library(plotly)
library(forcats)

mortality.rates <- read.csv("/Users/corinneriddell/Documents/repos/BlackWhiteMortalityGap/Results/mortality_rates_combined.csv")
mortality.rates.diff <- read.csv("/Users/corinneriddell/Documents/repos/BlackWhiteMortalityGap/Results/mortality_rates_diff_combined.csv")

mortality.rates <- mortality.rates %>% mutate(state.reorder = reorder(state, as.numeric(Census_Division))) %>% rename(Race = race)
mortality.rates.diff <- mortality.rates.diff %>% mutate(state.reorder = reorder(state, as.numeric(Census_Division))) 
```

```{r refactor-for-us-map-plot, echo=F}

# Create unique blank strip labels for empty facets
bl = sapply(1:37, function(n) paste(rep(" ",n),collapse=""))

mortality.rates$state.reorder2 <- factor(mortality.rates$state,
                                        levels = c(bl[1:10], "Maine",
                                                   bl[11:19], "Vermont", "New Hampshire",
                                                   "Washington", "Idaho", "Montana", "North Dakota", "Minnesota", "Illinois", "Wisconsin", "Michigan", "New York", "Massachusetts", "Rhode Island",
                                                   "Oregon", "Nevada", "Wyoming", "South Dakota", "Iowa", "Indiana", "Ohio", "Pennsylvania", "New Jersey", "Connecticut", bl[20],
                                                   "California", "Utah", "Colorado", "Nebraska", "Missouri", "Kentucky", "West Virginia", "Virginia", "Maryland", "Delaware", bl[21],
                                                   bl[22], "Arizona", "New Mexico", "Kansas", "Arkansas", "Tennessee", "North Carolina", "South Carolina", "Washington DC", bl[23:24],
                                                   bl[25:27], "Oklahoma", "Louisiana", "Mississippi", "Alabama", "Georgia", bl[28:29],
                                                   bl[30:33], "Texas", bl[34:37], "Florida"))

mortality.rates.diff$state.reorder2 <- factor(mortality.rates.diff$state,
                                        levels = c(bl[1:10], "Maine",
                                                   bl[11:19], "Vermont", "New Hampshire",
                                                   "Washington", "Idaho", "Montana", "North Dakota", "Minnesota", "Illinois", "Wisconsin", "Michigan", "New York", "Massachusetts", "Rhode Island",
                                                   "Oregon", "Nevada", "Wyoming", "South Dakota", "Iowa", "Indiana", "Ohio", "Pennsylvania", "New Jersey", "Connecticut", bl[20],
                                                   "California", "Utah", "Colorado", "Nebraska", "Missouri", "Kentucky", "West Virginia", "Virginia", "Maryland", "Delaware", bl[21],
                                                   bl[22], "Arizona", "New Mexico", "Kansas", "Arkansas", "Tennessee", "North Carolina", "South Carolina", "Washington DC", bl[23:24],
                                                   bl[25:27], "Oklahoma", "Louisiana", "Mississippi", "Alabama", "Georgia", bl[28:29],
                                                   bl[30:33], "Texas", bl[34:37], "Florida"))
```

```{r plotting_fx, echo = F}
plot.mortality.trends <- function(dataset, dataset2, COD1, sex1) {
  subset.data <- subset(dataset, COD == COD1 & sex == sex1)
  #lim.y <- c(min(subset.data$rate.per.100k_lcl), max(subset.data$rate.per.100k_ucl))
  
  subset.data2 <- subset(dataset2, sex == sex1 & COD == COD1)
  #lim.y2 <- c(min(subset.data2$rate.difference_LCL), max(subset.data2$rate.difference_UCL))
    
  a <- ggplot(subset.data, aes(x = year, y = rate.per.100k_mean)) + 
              geom_ribbon(aes(ymin = rate.per.100k_lcl, ymax = rate.per.100k_ucl, fill = Race), col = NA, alpha = 0.5) +
              geom_line(aes(col = Race)) +
              facet_wrap( ~ state.reorder2, ncol = 11, drop = F) +
              xlab(" ") + 
              ylab("Age-standardized mortality rate (per 100,000)") + 
              geom_hline(yintercept = 0, col = "black", lwd = 0.5) +
              #scale_y_continuous(limits = lim.y) + 
              ggtitle(paste0("Age-adjusted mortality (per 100,000) in ", sex1, " for ", COD1)) +
              theme_classic(base_size = 10) +
              theme(axis.text.x = element_blank(),
                    strip.background=element_blank(),
                    axis.line=element_blank(),
                    axis.ticks=element_blank()) 
             

  
  b <- ggplot(subset.data2, aes(x = year, y = rate.difference_mean)) + 
              geom_line() +
              geom_ribbon(aes(ymin = rate.difference_LCL, ymax = rate.difference_UCL), col = NA, alpha = 0.5) +
              facet_wrap( ~ state.reorder2, ncol = 11, drop = F) +
              xlab(" ") + 
              ylab("Excess mortality among blacks (per 100,000)") +
              #scale_y_continuous(breaks = 0) + #limits = lim.y2
              geom_hline(yintercept = 0, col = "black", lwd = 0.5) +
              #geom_vline(xintercept = 1969, col = "black", lwd = 0.5) +
              ggtitle(paste0("Excess mortality among blacks (per 100,000) in ", sex1, " for ", COD1)) +
              theme_classic(base_size = 10) +
              theme(panel.grid.minor = element_blank(),
                    axis.text.x = element_blank(),
                    strip.background=element_blank(),
                    axis.line=element_blank(),
                    axis.ticks=element_blank()) 
               
  
    return(list(plot1 = a, plot2 = b))
}
```

```{r create-the-plots, echo = F, message = F}
for(COD_i in levels(mortality.rates$COD)) {
  for(sex_i in levels(mortality.rates$sex)) {
    assign(paste0(COD_i, ".", sex_i, ".mort.plot"), plot.mortality.trends(dataset = mortality.rates, dataset2 = mortality.rates.diff,
                                                                         COD1 = COD_i, sex1 = sex_i))
  }
}
```

```{r print-em, fig.width = 9, fig.height = 9, echo = F}
ggplotly(Cardiovascular.Male.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Cardiovascular.Male.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))
```

```{r print-em-2, fig.width = 9, fig.height = 9, echo = F}
ggplotly(Cardiovascular.Female.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Cardiovascular.Female.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))
```

```{r print-em-3, fig.width = 9, fig.height = 9, echo = F}
ggplotly(Cancers.Male.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Cancers.Male.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))
```

```{r print-em-4, fig.width = 9, fig.height = 9, echo = F}
ggplotly(Cancers.Female.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Cancers.Female.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))
```

```{r print-3, fig.width = 9, fig.height=9, echo = F}
ggplotly(Communicable.Male.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Communicable.Male.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(Communicable.Female.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Communicable.Female.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(`Non-communicable.Male.mort.plot`[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(`Non-communicable.Male.mort.plot`[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(`Non-communicable.Female.mort.plot`[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(`Non-communicable.Male.mort.plot`[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(Injuries.Male.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Injuries.Male.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(Injuries.Female.mort.plot[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(Injuries.Female.mort.plot[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(`All other causes.Male.mort.plot`[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(`All other causes.Male.mort.plot`[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))

ggplotly(`All other causes.Female.mort.plot`[[1]]) %>% layout(xaxis = list(title = "Year (1969-2013)"), showlegend = F) 
ggplotly(`All other causes.Female.mort.plot`[[2]]) %>% layout(xaxis = list(title = "Year (1969-2013)"))
```

