---
output: html_document
bibliography: bibliography.bib
---

Corinne Riddell, PhD
Department of Epidemiology, Biostatistics & Occupational Health, 
McGill University, 
1020 Pine Avenue West
Montreal, QC
H2T 2E3
phone: 1-438-863-0402. email: <corinne.riddell@mail.mcgill.ca>


February 28^th^, 2017

Chief Editor, Larry Peiperl
*PLOS Medicine*

Dear Editors:

This presubmission inquiry is for our manuscript entitled, "Exploring how changes in cause of death have narrowed the black-white life expectancy gap in the United States". 

The measure of life expectancy serves as a barometer for the health of a nation. In 2014, life expectancy in the United States was 78.8 years, but hidden within this figure are differences by race. Whites lived 3.4 years longer than blacks [ref: http://www.cdc.gov/nchs/data/nvsr/nvsr65/nvsr65_04.pdf]. While both white and black Americans have generally experienced increases in life expectancy since the beginning of the 20^th^ century, the difference between their life expectancies has varied. During the 1980s, the life expectancy gap in the U.S. widened and then narrowed in the 1990s due largely to relative mortality improvements among blacks in deaths due to homicide, HIV, unintentional injuries, and, among females, due to differential improvements in heart disease [@harper2007trends]. The gap continued to narrow during the 2000s, but states differed markedly in the magnitude of improvement. For example, the life expectancy gap in New York decreased from 8.0 years to 2.4 years between 1990 and 2009, but in California the decrease was much more modest -- from 6.7 years to 5.6 years [@harper2014trends]. To-date, there are no published studies that have explored how changes in causes of death over time have contributed to wider life expectancy gaps in some states and narrower gaps in others. Thus, our objective was to **explore how changes in the cause of death over time have worked to narrow or exacerbate the life expectancy gap within each state between 1969 and 2013.**

**Insert what we found:**

We hope that you agree that our paper is suitable for submission to *PLOS Medicine*. Thank you for your consideration and we look forward to your response.

Sincerely, 

Corinne Riddell, PhD
Department of Epidemiology, Biostatistics & Occupational Health, 
McGill University, 
email: <corinne.riddell@mail.mcgill.ca>

**References**

