---
title: "Hispanic origin"
author: "Corinne Riddell"
date: "April 9, 2018"
output: word_document
---

```{r cancer}
library(tidyverse)
nh.cancer <- read.table("./Data/hispanic/NH Black and White Neoplasms.txt", header = T, nrows = 360, sep="\t")

nh.cancer <- nh.cancer %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "Non-hispanic")

all.cancer <- read.table("./Data/hispanic/All Black and White Neoplasms.txt", header = T, nrows = 360, sep="\t")

all.cancer <- all.cancer %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "All")

cancer <- dplyr::bind_rows(nh.cancer, all.cancer)

cancer2 <- cancer %>% 
  mutate(Race = plyr::revalue(Race, c("White" = "White",
                                      "Black or African American" = "Black")))

fig1 <- ggplot(cancer, aes(x = Year, y = Age.Adjusted.Rate)) + geom_line(aes(col = Race, lty = Hispanic.Origin)) + facet_grid(State~Gender)
```

```{r circulatory}
nh.circulatory <- read.table("../Data/hispanic/NH Black and White Circulatory.txt", header = T, nrows = 360, sep="\t")

nh.circulatory <- nh.circulatory %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "Non-hispanic")

all.circulatory <- read.table("../Data/hispanic/All Black and White Circulatory.txt", header = T, nrows = 360, sep="\t")

all.circulatory <- all.circulatory %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "All")

circulatory <- dplyr::bind_rows(nh.circulatory, all.circulatory)

circulatory2 <- circulatory %>% 
  mutate(Race = plyr::revalue(Race, c("White" = "White",
                                      "Black or African American" = "Black")))

fig2 <- ggplot(circulatory, aes(x = Year, y = Age.Adjusted.Rate)) + geom_line(aes(col = Race, lty = Hispanic.Origin)) + facet_grid(State~Gender)
```

```{r injuries}
nh.injuries <- read.table("./Data/hispanic/NH Black and White Injuries.txt", header = T, nrows = 360, sep="\t")

nh.injuries <- nh.injuries %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "Non-hispanic")

all.injuries <- read.table("./Data/hispanic/All Black and White Injuries.txt", header = T, nrows = 360, sep="\t")

all.injuries <- all.injuries %>% select(Year, Gender, Race, State, Deaths, Population, Crude.Rate, Age.Adjusted.Rate) %>%
  mutate(Hispanic.Origin = "All")

injuries <- dplyr::bind_rows(nh.injuries, all.injuries)

injuries2 <- injuries %>% 
  mutate(Race = plyr::revalue(Race, c("White" = "White",
                                      "Black or African American" = "Black")))

fig3 <- ggplot(injuries, aes(x = Year, y = Age.Adjusted.Rate)) + geom_line(aes(col = Race, lty = Hispanic.Origin)) + facet_grid(State~Gender)

ggplot(injuries, aes(x = Year, y = Age.Adjusted.Rate)) + geom_point(aes(col = Race, shape = Hispanic.Origin)) + facet_grid(State~Gender)
```

```{r}
ggsave(filename = "../Plots/Cancer.jpeg", plot = fig1, device = "jpeg", height = 9.5, width = 8, units = "in")
ggsave(filename = "../Plots/Cardiovacular.jpeg", plot = fig2, device = "jpeg", height = 9.5, width = 8, units = "in")
ggsave(filename = "../Plots/Injuries.jpeg", plot = fig3, device = "jpeg", height = 9.5, width = 8, units = "in")
```

