---
title: "Untitled"
output: html_document
---

```{r load_libraries}
library(dplyr)
library(purrr)
library(ggplot2)
library(stringr)
library(reshape2)
library(grid)
library(gridExtra)

source("~/BlackWhiteMortalityGap/Code/life_expectancy_functions.R")

```

```{r load_std_pop}
std.pop <- read.csv("~/BlackWhiteMortalityGap/Data/US_Standard_Population.csv")

std.pop <- std.pop %>% select(Age, US_Standard_2000) %>% filter(Age != "Total")

std.pop <- std.pop %>% mutate(age.weight = US_Standard_2000/1000000)

std.pop <- std.pop %>% mutate(age_minbin = 0*(Age == "00 years") + 1*(Age == "01-04 years") + 5*(Age == "05-09 years") +
                     10*(Age == "10-14 years") + 15*(Age == "15-19 years") + 20*(Age == "20-24 years") +
                     25*(Age == "25-29 years") + 30*(Age == "30-34 years") + 35*(Age == "35-39 years") +
                     40*(Age == "40-44 years") + 45*(Age == "45-49 years") + 50*(Age == "50-54 years") +
                     55*(Age == "55-59 years") + 60*(Age == "60-64 years") + 65*(Age == "65-69 years") +
                     70*(Age == "70-74 years") + 75*(Age == "75-79 years") + 80*(Age == "80-84 years") +
                     85*(Age == "85+ years"))
```

```{r calculate_age_std_mort_rates_and_bw_diff}
#this take a long time (a few hours!)

system.time(
  for(i in 1:8){
    print(i)
    load(paste0("~/BW_results/results_set_", i, ".Rdata"))
    r.All <- merge(r.All, std.pop, by = "age_minbin")
    
    #returns dataset with new variable "age.std.mortality.rate" 
    mortality.rates <- r.All %>% 
      group_by(post.samp, state.n, year.n, race.n, sex.n, COD) %>% 
      arrange(age_minbin) %>%
      summarise(age.std.mortality.rate = sum(age.weight*smoothed_rate), #the sum is across age bins
                race = first(race),
                sex = first(sex),
                state = first(state),
                year = first(year))
    
    mortality.rates.summary <- mortality.rates %>% group_by(state.n, year.n, race.n, sex.n, COD) %>%
      summarise(race = first(race),
                sex = first(sex),
                state = first(state),
                year = first(year),
                age.std.mortality.rate_LCL = quantile(age.std.mortality.rate, 0.025), #summarize across posterior samples (post.samp)
                age.std.mortality.rate_med = quantile(age.std.mortality.rate, 0.5),
                age.std.mortality.rate_UCL = quantile(age.std.mortality.rate, 0.0975))
    
    #tidy mortality rates summary
    COD.levels <- c("Cardiovascular", "Cancers", "Communicable", 
                    "Non-communicable", "Injuries", "All other causes")
    
    mortality.rates.summary$COD <- factor(mortality.rates.summary$COD, COD.levels)
    
    mortality.rates.summary <- add_Census_Division(mortality.rates.summary, state)
    mortality.rates.summary <- add_Census_Region(mortality.rates.summary, state)
    mortality.rates.summary$stabbrs <- state.abb[match(mortality.rates.summary$state, state.name)]
    mortality.rates.summary$rate.per.100k <- mortality.rates.summary$age.std.mortality.rate_med*100000
    mortality.rates.summary <- mortality.rates.summary %>% mutate(state.reorder = reorder(state, as.numeric(Census_Division)))

    #compute black-white difference in mortality
    mortality.rates.white <- mortality.rates %>% filter(race == "White") %>% 
      ungroup() %>%
      select(sex, state, year, COD, post.samp, age.std.mortality.rate) %>%
      rename(age.std.mortality.rate.white = age.std.mortality.rate)
    
    mortality.rates.black <- mortality.rates %>% filter(race == "Black") %>% 
      rename(age.std.mortality.rate.black = age.std.mortality.rate)  
    
    mortality.rates.wide <- merge(mortality.rates.black, mortality.rates.white, by = c("post.samp", "sex", "state", "year", "COD"))
    
    mortality.rates.wide <- mortality.rates.wide %>% mutate(rate.difference = age.std.mortality.rate.black - age.std.mortality.rate.white)
    
    mortality.rates.difference <- mortality.rates.wide %>% 
      group_by(state.n, year.n, sex.n, COD) %>%
      summarise(rate.difference_LCL = quantile(rate.difference, 0.025), #summarize across posterior samples (post.samp)
                rate.difference_med = quantile(rate.difference, 0.5),
                rate.difference_UCL = quantile(rate.difference, 0.0975),
                sex = first(sex),
                state = first(state),
                year = first(year))
    
    mortality.rates.difference %>% mutate(state.reorder = reorder(state, as.numeric(Census_Division)))
    
    write.csv(mortality.rates.summary, paste0("~/BlackWhiteMortalityGap/Data/mortality_rates_", i, ".csv"))
    write.csv(mortality.rates.difference, paste0("~/BlackWhiteMortalityGap/Data/mortality_rates_diff_", i, ".csv"))
  }
)
```







