---
title: "Untitled"
author: "Corinne Riddell"
date: "November 8, 2016"
output: html_document
---

```{r setup, include=FALSE}
library(plyr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(plotly)
source("/Users/corinneriddell/Documents/repos/BlackWhiteMortalityGap/Code/life_expectancy_functions.R")
```

```{r load datasets}
dat.male <- read.table("/Users/corinneriddell/Dropbox/BlackWhiteGap/Data/males_export.txt", header = T, sep="\t", na.strings = " ")
names(dat.male) <- c("State", "Age", "Sex", "Race", "COD", "Year", "Crude_Rate", "Count", "Population")
prop.table(table(is.na(dat.male$Count)))
head(dat.male)
table(dat.male$Sex)
str(dat.male) #note all numeric or int

dat.female <- read.table("/Users/corinneriddell/Dropbox/BlackWhiteGap/Data/female_export.txt", header = T, sep="\t", na.strings = " ")
names(dat.female) <- c("State", "Age", "Sex", "Race", "COD", "Year", "Crude_Rate", "Count", "Population")
table(dat.female$Sex)
dat.female$Sex <- 1
str(dat.male) #note all numeric or int

prop.table(table(is.na(dat.female$Count)))
head(dat.female)

dat.both <- rbind(dat.male, dat.female)

rm(dat.male, dat.female)
```

```{r load_COD_dictionary}
cod.dict <- read.csv("/Users/corinneriddell/Dropbox/BlackWhiteGap/Data/COD_dictionary.csv")

cod.dict$COD2 <- reorder(cod.dict$COD, cod.dict$COD_num)
levels(cod.dict$COD2)

cod.dict$cod_cat <- "Cancers"

cod.dict$cod_cat[cod.dict$COD2 == "Diseases of Heart" | 
                 cod.dict$COD2 == "Hypertension without Heart Disease" |
                 cod.dict$COD2 == "Cerebrovascular Diseases" |  
                 cod.dict$COD2 == "Atherosclerosis" |  
                 cod.dict$COD2 == "Aortic Aneurysm and Dissection" | 
                 cod.dict$COD2 == "Other Diseases of Arteries, Arterioles, Capillaries"] <- "Cardiovascular"

cod.dict$cod_cat[cod.dict$COD2 == "Tuberculosis" | 
                 cod.dict$COD2 == "Syphilis" |
                 cod.dict$COD2 == "Human Immunodeficiency Virus (HIV) (1987+)" |  
                 cod.dict$COD2 == "Septicemia" |  
                 cod.dict$COD2 == "Other Infectious and Parasitic Diseases" | 
                 cod.dict$COD2 == "Pneumonia and Influenza"] <- "Communicable"

cod.dict$cod_cat[cod.dict$COD2 == "Diabetes Mellitus" | 
                 cod.dict$COD2 == "Alzheimers (ICD-9 and 10 only)" |
                 cod.dict$COD2 == "Chronic Obstructive Pulmonary Disease and Allied Cond" |  
                 cod.dict$COD2 == "Stomach and Duodenal Ulcers" |  
                 cod.dict$COD2 == "Chronic Liver Disease and Cirrhosis" | 
                 cod.dict$COD2 == "Nephritis, Nephrotic Syndrome and Nephrosis"] <- "Non-communicable" 

cod.dict$cod_cat[cod.dict$COD2 == "Accidents and Adverse Effects" | 
                 cod.dict$COD2 == "Suicide and Self-Inflicted Injury" |
                 cod.dict$COD2 == "Homicide and Legal Intervention"] <- "Injuries" 

cod.dict$cod_cat[cod.dict$COD2 == "Complications of Pregnancy, Childbirth, Puerperium" | 
                 cod.dict$COD2 == "Congenital Anomalies" |
                 cod.dict$COD2 == "Certain Conditions Originating in Perinatal Period" |  
                 cod.dict$COD2 == "Symptoms, Signs and Ill-Defined Conditions" |  
                 cod.dict$COD2 == "Other Cause of Death"] <- "All other causes" 

cod.dict <- cod.dict[ ,-2]
```


```{r recode_variables}
dat.both <- dat.both %>%
  mutate(State2 = factor(State, levels = c(0:50), labels = c("Alabama", "Alaska", "Arizona", "Arkansas","California",
                                                             "Colorado", "Connecticut", "Delaware", "Washington DC",
                                                             "Florida", "Georgia", "Hawaii","Idaho", "Illinois", 
                                                             "Indiana","Iowa", "Kansas", "Kentucky", "Louisiana", 
                                                             "Maine", "Maryland", "Massachusetts", "Michigan", 
                                                             "Minnesota", "Mississippi","Missouri", "Montana", 
                                                             "Nebraska", "Nevada", "New Hampshire", "New Jersey",
                                                             "New Mexico", "New York","North Carolina","North Dakota",
                                                             "Ohio", "Oklahoma","Oregon", "Pennsylvania", 
                                                             "Rhode Island", "South Carolina", "South Dakota", 
                                                             "Tennessee", "Texas", "Utah", "Vermont", "Virginia",
                                                             "Washington", "West Virginia", "Wisconsin", "Wyoming")), 
         Age2 = factor(Age, levels = c(0:19), labels = c("<1 year", "1-4 years", "5-9 years", "10-14 years", 
                                                         "15-19 years", "20-24 years", "25-29 years", "30-34 years",
                                                         "35-39 years", "40-44 years", "45-49 years", "50-54 years", 
                                                         "55-59 years", "60-64 years", "65-69 years", "70-74 years", 
                                                         "75-79 years", "80-84 years","85+ years", "Unknown"), ordered = T),
         Age3 = 0*(Age2 == "<1 year") + 1*(Age2 == "1-4 years") + 5*(Age2 == "5-9 years") +
                10*(Age2 == "10-14 years") + 15*(Age2 == "15-19 years") + 20*(Age2 == "20-24 years") + 
                25*(Age2 == "25-29 years") + 30*(Age2 == "30-34 years") + 35*(Age2 == "35-39 years") +
                40*(Age2 == "40-44 years") + 45*(Age2 == "45-49 years") + 50*(Age2 == "50-54 years") + 
                55*(Age2 == "55-59 years") + 60*(Age2 == "60-64 years") + 65*(Age2 == "65-69 years") +   
                70*(Age2 == "70-74 years") + 75*(Age2 == "75-79 years") + 80*(Age2 == "80-84 years") + 
                85*(Age2 == "85+ years"),
         nx = 1*(Age2 == "<1 year") + 4*(Age2 == "1-4 years") + 5*(Age2 != "<1 year" & Age2 != "1-4 years"),
         Sex2 = factor(Sex, levels = c(0, 1), labels = c("Male", "Female")),
         Race2 = factor(Race, levels = c(0, 1), labels = c("White", "Black")),
         COD2 = factor(COD, levels = c(0:92), labels = levels(cod.dict$COD2)), 
         Year2 = factor(Year, levels = c(0:44), labels = as.character(1969:2013)),
         Year3 = as.numeric(as.character(Year2)),
         RaceSex = interaction(Race2, Sex2, sep = " "),
         StateYearSex = interaction(State2, Year2, Sex2),
         StateYearRaceSex = interaction(State2, Year2, Race2, Sex2))

dim(dat.both)
dat.both <- merge(dat.both, cod.dict, by = "COD2") #to add on COD_num and cod_cat
dim(dat.both)
```

```{r pull_alabama}
alabama.males <- dat.both %>% filter(State2 == "Alabama", Sex2 == "Male")

save(alabama.males, file = "/Users/corinneriddell/Dropbox/BlackWhiteGap/Data/alabama_males_granular.Rdata")
```

